### ISSUE TITLE
Demo site not loding

### ISSUE THREAD

**Issue by sturlath** [abpframework/cms-kit-demo#7]
@EngincanV  the site is out

![image](https://github.com/abpframework/cms-kit-demo/assets/2386572/b7bea18d-4222-45c4-af6d-cdf2eab58948)

**Comment by EngincanV** [comment]
> @EngincanV  the site is out
> 
> ![image](https://github.com/abpframework/cms-kit-demo/assets/2386572/b7bea18d-4222-45c4-af6d-cdf2eab58948)
> 

The website is not live yet.

**Comment by EngincanV** [comment]
The website is live at https://cms-kit-demo.abpdemo.com/
